# Generated by Django 4.0.4 on 2022-04-22 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=200)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('Private', models.BooleanField(default=False)),
            ],
        ),
    ]
